### ISSUE TITLE
head folder in api_library

### ISSUE THREAD

**Issue by Johnweii25** [nakulbende/ALP41_API_Matlab#1]
Hi,nakul.When i am running the api_control,i found an error:can't found the alpbasic.h,i had search in the ALP-4.3 API,it seems that there isn't exist.Is there some codes that should be changed or can you give me some advice?Thanks!
![image](https://github.com/nakulbende/ALP41_API_Matlab/assets/147235455/e82b7016-7b5d-49e8-b4f1-4ecf6543f53d)

**Comment by nakulbende** [comment]
Do you already have the drivers installed? If I remember correctly they are
installed by the software directly from vendor-
https://www.vialux.de/en/download.html

Nakul Prabhakar Bende, PhD

Materials Scientist, Formlabs Inc.

http://nakulbende.com

- Ever tried. Ever failed. Try Again. Fail again. Fail better.

--Samuel Beckett

**Comment by Johnweii25** [comment]
I see where the file is.Thank you for your reply!
